# Generated by Django 5.0.7 on 2024-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_room_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_paused',
            field=models.BooleanField(default=True),
        ),
    ]
